# Generated by Django 6.0.3 on 2026-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('vitals_recorded', 'Vitals Recorded'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('noshow', 'No Show')], default='scheduled', max_length=20),
        ),
    ]
