# Generated by Django 6.0.3 on 2026-03-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Body temperature in Celsius', max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5)),
                ('heart_rate', models.PositiveIntegerField(help_text='Beats per minute')),
                ('blood_pressure', models.CharField(help_text='Example: 120/80', max_length=15)),
                ('recorded_by', models.CharField(help_text='Name of the nurse recording vitals', max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
            ],
        ),
    ]
